version: '3.0'

services:
  nginx:
    image: docker.pkg.github.com/netcracker-education-center/collect-and-search-ui/reactimage:latest
    restart: unless-stopped
    ports:
      - 7070:7070
      - 443:443
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - "docker-network"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      depends_on:
        - nginx
      command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --staging -d netcracker-collect-and-search.tk -d www.netcracker-collect-and-search.tk

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/netcracker/ui/
      o: bind

networks:
  docker-network:
    external: true
