FROM node:13.1-alpine as build

WORKDIR /usr/src/app
COPY package*.json ./
COPY . ./
RUN npm install --legacy-peer-deps && npm run build

# Stage - Production
FROM nginx:1.17-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]