version: "3"
services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - "7070:7070"
    volumes:
      - ./app
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7071:7071"
    volumes:
      - ./server:/usr/src/app
    