name: build

on:
  push:
    branches: 
      - ci-cd

jobs:
  build:
    runs-on: ubuntu-latest
    name: Save prodaction build in Docker to GitHub packages
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 13.10
      uses: actions/setup-node@v1
      with:
        node-version: '13.10'
    - name: Install npm
      run: |
        npm install
      env:
        CI: true
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: netcracker-education-center/collect-and-search-ui/reactimage
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile
        tags: latest 
        
    - name: Deploy package to digitalocean        
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.PASSPHRASE}}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
             docker login https://docker.pkg.github.com -u ${{github.repository_owner}} -p ${{secrets.GITHUB_TOKEN}} --password-stdin
             docker container stop $(docker ps -aqf "name=reactimage")
             docker container rm $(docker ps -aqf "name=reactimage")
             docker image rm netcracker/reactimage
             docker image rm docker.pkg.github.com/netcracker-education-center/data-collector/reactimage
             docker pull docker.pkg.github.com/netcracker-education-center/collect-and-search-ui/reactimage:latest
             docker run -dit -p 4040:4040 docker.pkg.github.com/netcracker-education-center/collect-and-search-ui/reactimage:latest

  #             cd netcracker/education-center/collect-and-search/collect-and-search-ui
  #             docker login https://docker.pkg.github.com -u ${{github.repository_owner}} -p ${{secrets.GITHUB_TOKEN}} --password-stdin
  #             docker container stop $(docker ps -aqf "name=reactimage")
  #             docker container rm $(docker ps -aqf "name=reactimage")
  #             docker image rm netcracker/reactimage
  #             docker image rm docker.pkg.github.com/netcracker-education-center/collect-and-search-ui/reactimage
  #             docker pull docker.pkg.github.com/netcracker-education-center/collect-and-search-ui/reactimage:latest
  #             docker tag docker.pkg.github.com/netcracker-education-center/collect-and-search-ui/reactimage:latest netcracker/reactimage:latest
  #             # -d means that container starts in detached mode or in the background
  #             docker run -d --name reactimage -p 3000:3000 -p 7070:7070 netcracker/reactimage:latest -v netcracker/education-center/collect-and-search/collect-and-search-ui/log:/log

