name: build

on:
  push:
    branches: 
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 13.10
      uses: actions/setup-node@v1
      with:
        node-version: '13.10'
    - name: Install npm
      run: |
        npm install --legacy-peer-deps
    - name: Publish to Github Packages Registry
      uses: docker/build-push-action@v1
      with:
        repository: netcracker-education-center/collect-and-search-ui/reactimage
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile
        tags: latest
        tag_with_ref: true
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        passphrase: ${{secrets.PASSPHRASE}}
        script: |
          cd netcracker/collect-and-search/collect-and-search-ui
          docker login https://docker.pkg.github.com -u ${{github.repository_owner}} -p ${{secrets.GITHUB_TOKEN}}
          docker container stop $(docker ps -aqf "name=reactimage")
          docker container rm $(docker ps -aqf "name=reactimage")
          docker image rm netcracker/reactimage
          docker image rm docker.pkg.github.com/netcracker-education-center/collect-and-search-ui/reactimage
          docker pull docker.pkg.github.com/netcracker-education-center/collect-and-search-ui/reactimage:latest
          docker tag docker.pkg.github.com/netcracker-education-center/collect-and-search-ui/reactimage:latest netcracker/reactimage:latest
          # -d means that container starts in detached mode or in the background

          docker run -d --name reactimage  -v /nginx/nginx.conf:/etc/nginx/conf.d -p 7070:7070 --network=docker-network netcracker/reactimage:latest
